# Java Gradle CircleCI 2.1 configuration file
#
# Check https://circleci.com/docs/2.1/language-java/ for more details
#
version: 2.1
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/openjdk:11-jdk

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    branches:
      only:
        - dev

    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: sh gradlew dependencies --refresh-dependencies

      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}

      # run Build!
      - run: sh gradlew build

  test:
    # run tests!
    - run: sh gradlew test --refresh-dependencies

  code_quality:
    docker:
      # specify the version you desire here
      - image: circleci/openjdk:11-jdk

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    branches:
      only:
        - dev

    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}

      # run tests!
      - run: sh gradlew test

      # Code Quality Metrics (Sonarqube) >> Code Quality Metrics (Sonarqube)
      - run: ./gradlew sonarqube
          -Dsonar.projectKey=sean-huni_twitch
          -Dsonar.organization=sean-huni-github
          -Dsonar.host.url=https://sonarcloud.io
          -Dsonar.login=162248aeafe59568304caa3c2e4276a7418e0525

workflows:
  main:
    jobs:
      - build
      - test:
          requires:
            - build
      - code_quality:
          requires:
            - test